const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function setup(){const c=vm.createContext({window:{}});for(const f of ['dvc-dates.js','dvc-point-attention.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',f),'utf8'),c);return c;}
const today={year:2026,month:9,day:22};
const contract=(id,use_year)=>({id,use_year,is_active:true,points_per_year:150});
test('holding-only balance is actionable without an entry date',()=>{const c=setup(),a=contract('a','Oct');const s=c.window.DVCPointAttention.evaluate(a,{a:[{use_year_label:2025,balance_confirmed_at: '2026-09-22', points_remaining:0,points_holding:10}]},today);assert.equal(s.kind,'use-by');assert.equal(s.points,10);assert.equal(s.expiresMs,Date.UTC(2026,8,30));assert.equal(s.daysUntil,8);});
test('earlier expiration outranks an open but later banking deadline',()=>{const c=setup(),a=contract('a','Oct'),b=contract('b','Apr');const s=c.window.DVCPointAttention.earliest([b,a],{a:[{use_year_label:2025,balance_confirmed_at: '2026-09-22', points_remaining:0,points_holding:10}],b:[{use_year_label:2026,balance_confirmed_at: '2026-09-22', points_remaining:50}]},today);assert.equal(s.contract.id,'a');});
test('banked and borrowed balances prevent false all-clear',()=>{const c=setup(),a=contract('a','Feb');for(const field of ['points_banked','points_borrowed']){const s=c.window.DVCPointAttention.evaluate(a,{a:[{use_year_label:2026,balance_confirmed_at: '2026-09-22', points_remaining:0,[field]:20}]},today);assert.equal(s.kind,'use-by');assert.equal(s.points,20);}});
test('current and nonbankable points expose distinct actions when banking is open',()=>{const c=setup(),a=contract('a','Apr');const events=c.window.DVCPointAttention.eventsForContract(a,{a:[{use_year_label:2026,balance_confirmed_at: '2026-09-22', points_remaining:50,points_holding:10,points_banked:20,points_borrowed:5}]},today);assert.equal(events.length,2);assert.equal(events[0].kind,'bankable');assert.equal(events[0].points,50);assert.equal(events[1].points,35);});
test('all-clear requires every current-cycle bucket to be empty',()=>{const c=setup(),a=contract('a','Oct');const s=c.window.DVCPointAttention.earliest([a],{a:[{use_year_label:2025,balance_confirmed_at: '2026-09-22', points_remaining:0,points_holding:0,points_banked:0,points_borrowed:0}]},today);assert.equal(s.kind,'accounted');});
test('inactive contracts do not generate action warnings',()=>{const c=setup();assert.equal(c.window.DVCPointAttention.earliest([{...contract('a','Oct'),is_active:false}],{},today),null);});
test('use-year rollover selects the next cycle',()=>{const c=setup(),a=contract('a','Oct');const rows={a:[{use_year_label:2025,balance_confirmed_at: '2026-09-22', points_remaining:0,points_holding:10},{use_year_label:2026,balance_confirmed_at: '2026-09-22', points_remaining:0}]};assert.equal(c.window.DVCPointAttention.evaluate(a,rows,{year:2026,month:10,day:1}).kind,'accounted');});
for(const file of ['home.js','account.html'])test(file+' uses shared deadline selection',()=>{const c=setup(),source=fs.readFileSync(path.join(__dirname,'..',file),'utf8');for(const name of ['evaluateContractDeadlineStatus','computeEarliestDeadline'])vm.runInContext(source.match(new RegExp('function '+name+'\\([^]*?\\n\\}'))[0],c);assert.equal(c.computeEarliestDeadline([contract('a','Oct')],{a:[{use_year_label:2025,balance_confirmed_at: '2026-09-22', points_remaining:0,points_holding:10}]},today).kind,'use-by');});
test('missing balance is unknown rather than an allotment or all-clear',()=>{const c=setup(),a=contract('a','Oct');const s=c.window.DVCPointAttention.earliest([a],{},today);assert.equal(s.kind,'unconfirmed');assert.equal(s.points,undefined);});
test('stored but unconfirmed draft never creates a banking warning',()=>{const c=setup(),a=contract('a','Apr');assert.equal(c.window.DVCPointAttention.evaluate(a,{a:[{use_year_label:2026,points_remaining:150}]},today).kind,'unconfirmed');});
test('known deadlines stay ahead of unknown balances',()=>{const c=setup(),a=contract('a','Oct'),b=contract('b','Apr');const s=c.window.DVCPointAttention.earliest([b,a],{a:[{use_year_label:2025,balance_confirmed_at:'2026-09-22',points_remaining:0,points_holding:10}]},today);assert.equal(s.contract.id,'a');});
